### ISSUE TITLE
Edge case lib/jt65 segfaults

### ISSUE THREAD

**Issue by pdogg** [pdogg/jt65stego#18]
the jt65 decoder binary seems to segfault on some edge decode_rs_int and unpackmsg cases from onair packets... 

```
Processing /home/pdogg/shares/wsjtsaves/140526_1429.wav file...                                                                                                            
 32 23  5 56 61 13 26 34 13 27 59  0 29 42 45 16 46 27 40 26 12 63 46 22 44 33 45 53 28 22 35  9 31 25 48  8 21 60 12 17  7 63 42 48 31 36 60 61 43 16 31 42 41 47 15  7 54 30 32 61 43 53 24                                                                                                                                                         
 255 255  33  52 255 255   7 255 255 255 255  87  29 255 255 255 255 255 104 221 255 255 226 255  11 255 254 255   7 255 255  28   5 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 148   4 240 250 255 255 255 255 255 255 255 255                                                                                          
 CQ KB4DCG EM78        ,   581.404846     ,   588.867188     ,   1.04241276     ,  -6.45481944E-02                                                                         

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.                                                                                            

Backtrace for this error:                                                                                                                                                  
#0  0x7FC9A3EF9667                                                                                                                                                         
#1  0x7FC9A3EF9C34                                                                                                                                                         
#2  0x7FC9A34B84EF                                                                                                                                                         
#3  0x7FC9A45FD237                                                                                                                                                         
#4  0x7FC9A45FDC01                                                                                                                                                         
#5  0x7FC9A46019F1                                                                                                                                                         
#6  0x7FC9A4607A54                                                                                                                                                         
#7  0x4099C5 in decode_rs_int                                                                                                                                              
#8  0x40835C in rs_decode_ at wrapkarn.c:71                                                                                                                                
#9  0x40692F in extract_ at extract.F90:55                                                                                                                                 
#10  0x406027 in decode65b_ at decode65b.f90:25                                                                                                                            
#11  0x404DCA in decode65a_ at decode65a.f90:90                                                                                                                            
#12  0x40324C in jt65a_ at jt65a.f90:57                                                                                                                                    
#13  0x401CEC in jt65 at jt65.f90:55                                                                                                                                       
Segmentation fault                                                                                                                                                         

Processing /home/pdogg/shares/wsjtsaves/140526_1710.wav file...
 61 22 20 48 62 50 21 33 57 29 37 54 28  8  0 43  7 12 19 17 35 41  7 20 54  8 15 22 48 17 17 53 49 61 62 13  8 63 36 11 30  6 31  9  8 15 46  5 54 39 25 34 23 36 42 43 10 53 17 55 37 55 18
 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 241 245  70  11   4   4   4   6   8  28  26  41  85  73 164 196  86  91 162 203  22
 ANT WINDOM            ,   1303.39160     ,   1248.04688     ,  0.132221282     ,  -4.25325036E-02
  5  0  0 53 51 35 60 28 62 14 25 19 15 40 35 59 58 62 56 21  7 49 28 53 51 33 56 48 16 54 60 13 60  9 48 45 61 28  1 45 36  6 55 48  7 23 21 60 48 49 20 26 41 47 31 14 17 28 40 40 30 52 14
 230 255 255 104  17   6   8   8  14   6   5   6   5   5   9   8   7   5 174 254 122  11  31 146 206 145 211 196 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7F0D92D9F667
#1  0x7F0D92D9FC34
#2  0x7F0D9235E4EF
#3  0x7F0D934A3237
#4  0x7F0D934A3C01
#5  0x7F0D934A79F1
#6  0x7F0D934ADA54
#7  0x40BC40 in unpackmsg_ at unpackmsg.f90:60
#8  0x406A8F in extract_ at extract.F90:61Processing /home/pdogg/shares/wsjtsaves/140526_1737.wav file...
 32 23  5 56 61 13 26 34 13 27 59  0 29 42 45 16 46 27 40 26 12 63 46 22 44 33 45 53 28 22 35  9 31 25 48  8 21 60 12 17  7 63 42 48 31 36 60 61 43 16 31 42 41 47 15  7 54 30 32 61 43 53 24
 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255  92   9   6 253 255 255 254 255 255 255 255 242 171 235  12  10   6  33  11  16  73  39 255 239 254 239 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
 CQ KB4DCG EM78        ,   1039.65442     ,   1341.79688     ,   3.95660663     ,  -5.34005165E-02
 23 37 12 11 44  3 36 42 44 48 29 29  7 20 54 28 59 41  7 13 30  3 58 13 23 32 60 58 27 40 51 43  9 37 46 38 37 62 19 53 46 57 24  9  7 17 17 44 17 63 43 22  2 47 23 26 25 18 50 55 47  2 27
  12  87 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255  18  13 253 243 252 255 255 151 199 229  11   8   6   4   4   6   4   4   4   4   4   4  13  50  24 180  13   4   4   4   4   4   4   4

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7F0BB74E0667
#1  0x7F0BB74E0C34
#2  0x7F0BB6A9F4EF
#3  0x7F0BB7BE4237
#4  0x7F0BB7BE4C01
#5  0x7F0BB7BE89F1
#6  0x7F0BB7BEEA54
#7  0x40ADBA in unpackmsg_ at unpackmsg.f90:46
#8  0x406A8F in extract_ at extract.F90:61
#9  0x406027 in decode65b_ at decode65b.f90:25
#10  0x404DCA in decode65a_ at decode65a.f90:90
#11  0x40324C in jt65a_ at jt65a.f90:57
#12  0x401CEC in jt65 at jt65.f90:55
Segmentation fault

#9  0x406027 in decode65b_ at decode65b.f90:25
#10  0x404DCA in decode65a_ at decode65a.f90:90
#11  0x40324C in jt65a_ at jt65a.f90:57
#12  0x401CEC in jt65 at jt65.f90:55
Segmentation fault
```

**Comment by pdogg** [comment]
```
$ cat crashtest.py 
import jt65wrapy as jt

unpackcrash1 = [5,  0,  0, 53, 51, 35, 60, 28, 62, 14, 25, 19, 15, 40, 35, 59, 58, 62, 56, 21,  7, 49, 28, 53, 51, 33, 56, 48, 16, 54, 60, 13, 60,  9, 48, 45, 61, 28,  1, 45, 36,  6, 55, 48,  7, 23, 21, 60, 48, 49, 20, 26, 41, 47, 31, 14, 17, 28, 40, 40, 30, 52, 14]

test1 = jt.unprepmsg(unpackcrash1)
print test1
test2 = jt.decode(test1)
print test2
```

Expected segfault but doesn't...
[62 32 32 49 39 55  7 47 54  5 53 11]
CQ K4YZZ EM73

**Comment by pdogg** [comment]
unpackmsg segfault happens at

60:         grid6=grid//'ma'

**Comment by pdogg** [comment]
seems no matter what I do with that concatenation it sigsegv 
Passes all tests with the following ... don't know if we encounter any cases where this breaks something... 

 61   grid6=grid
 62 ! grid6=grid//'ma' <- orig line... segfaults debian wheezy wtf

**Comment by pdogg** [comment]
rs testcase

```
       8          62          61          60          19           4          16           1          21          50          12          21          31          18          29          15          27           8          29          14          30          50          23          26          19          32          56          32          21           8          20          32          60          61          59          23          61          32          58           5          55          52          29          32          26          62           1          32          33          57          51          26           6          16          14          46          61          43          27          53          28          45          60
      22          20         127         248          71         255         255          14          15          11          14         124         255          85         229          14          27         138         254          84         255         255         111         255          28         128         252          12         227          18          76         248          20          26          11           8         149          12          12         186          59          16          50           7           7           7           7         107          10          70          10          37           7           8          12         252          69          16          29         186         254          34           8
```

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7F0A71EE2667
#1  0x7F0A71EE2C34
#2  0x7F0A714A14EF
#3  0x7F0A725E6237
#4  0x7F0A725E6C01
#5  0x7F0A725EA9F1
#6  0x7F0A725F0A54
#7  0x4088C5 in decode_rs_int
#8  0x40725C in rs_decode_ at wrapkarn.c:71
#9  0x40582F in extract_ at extract.F90:57
#10  0x404E27 in decode65b_ at decode65b.f90:25
#11  0x403BCA in decode65a_ at decode65a.f90:90
#12  0x40208C in jt65a_ at jt65a.f90:57
#13  0x401B2C in jt65 at jt65.f90:55
Segmentation fault

Still decoded fine... weird prefix..

[63 45 63  4 54 25 15 47 26 19 31 40]
DE S817/MO3YHL KJ02

**Comment by pdogg** [comment]
There's absolutely something wrong with wheezy... Same code, same compile options doesn't segfault on ubuntu 14.04

**Comment by pdogg** [comment]
Closing for now... This could cause a problem with on air decodes on the pi with raspian... if it does we can find it and fix it later. For bad on air decodes at the moment use ubuntu 14.04
